In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [4]:
a1.shape

(5,)

In [5]:
a2 = np.array([[1,2,3,4,5], 
             [6,7,8,9,10]])
a2, a2.shape


(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 (2, 5))

In [6]:
a3 = np.array([[[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25],
                [26,27,28,29,30]],
               [[31,32,33,34,35],
                [36,37,38,39,40],
                [41,42,43,44,45],
                [46,47,48,49,50],
                [51,52,53,54,55],
                [56,57,58,59,60]]])
a3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [7]:
a3.shape

(2, 6, 5)

In [8]:
sample_array = np.array([1,2,3,4,5])
sample_array

array([1, 2, 3, 4, 5])

In [9]:
ones = np.ones((2,3), dtype=int)

In [10]:
ones.dtype

dtype('int64')

In [11]:
range_array = np.arange(0,10, 2)
range_array

array([0, 2, 4, 6, 8])

In [12]:
random_array = np.random.randint(0,100, size=(3,5))

In [13]:
random_array

array([[ 7, 84, 91, 22, 69],
       [75, 84, 38, 73, 36],
       [39, 77, 22, 71, 20]])

In [14]:
np.random.seed(42)
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

## 4. Manipulating Arrays

### Arithmetic Operations

In [15]:
a1 = np.array([1,2,3])

In [16]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [17]:
a1 + ones, a1 - ones

(array([2., 3., 4.]), array([0., 1., 2.]))

In [18]:
a1 * ones

array([1., 2., 3.])

In [19]:
a2 = np.array([[1,2,3],
               [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [21]:
a1.shape, a2.shape

((3,), (2, 3))

In [22]:
a3 = np.random.randint(0,10, size=(2,3,3))

In [23]:
a3.shape

(2, 3, 3)

In [24]:
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

In [25]:
a2/a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [26]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [27]:
np.sqrt(a2**2)

array([[1., 2., 3.],
       [4., 5., 6.]])

### Aggregation

aggregation = performaing the same operation on all elements of the array

In [28]:
l = np.array([1,2,3])

In [29]:
np.sum(l)

np.int64(6)

In [30]:
big_array = np.random.random(1000000)
big_array.size

1000000

In [31]:
%timeit sum(big_array)
%timeit np.sum(big_array)

53.1 ms ± 1.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
159 μs ± 2.95 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [32]:
np.mean(big_array)

np.float64(0.5003374309681168)

In [33]:
np.std(big_array)

np.float64(0.28859107863345884)

In [34]:
np.var(big_array)

np.float64(0.08328481066682324)

# Demo of std and var

In [35]:
high_variance = np.array([1,100,200,300,4000,5000])
low_variance = np.array([2,4,6,8,10])

In [36]:
np.std(high_variance), np.var(high_variance)

(np.float64(2072.711623024829), np.float64(4296133.472222221))

In [37]:
np.std(low_variance), np.var(low_variance)

(np.float64(2.8284271247461903), np.float64(8.0))

In [38]:
np.mean(high_variance), np.mean(low_variance)

(np.float64(1600.1666666666667), np.float64(6.0))

# Transposing and reshaping

In [39]:
a2.shape

(2, 3)

In [40]:
a3.shape

(2, 3, 3)

In [41]:
a3

array([[[4, 1, 7],
        [5, 1, 4],
        [0, 9, 5]],

       [[8, 0, 9],
        [2, 6, 3],
        [8, 2, 4]]])

In [42]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a2_reshaped = a2.reshape(2,3,1)

In [44]:
a2_reshaped.shape

(2, 3, 1)

In [45]:
a2_reshaped * a3

array([[[ 4,  1,  7],
        [10,  2,  8],
        [ 0, 27, 15]],

       [[32,  0, 36],
        [10, 30, 15],
        [48, 12, 24]]])

In [46]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
a3.shape

(2, 3, 3)

# Dot Product

In [48]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))


In [49]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [50]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [51]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [52]:
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [53]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [54]:
mat1.dot(mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [55]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [56]:
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, 
                            index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                            columns=['Almond', 'Cashew', 'Pistachio'])

In [57]:
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [58]:
prices_df = pd.DataFrame(prices.reshape(1,3), index=['Prices'],
                         columns=['Almond', 'Cashew', 'Pistachio'])
prices_df

Almond  Cashew  Pistachio
Prices      10       8         12

In [59]:
prices_df.shape, weekly_sales.shape

((1, 3), (5, 3))

In [60]:
weekly_sales['total']= prices_df.dot(weekly_sales.T).T

In [61]:
weekly_sales

Almond  Cashew  Pistachio  total
Mon      12      15          0    240
Tue       3       3          7    138
Wed       9      19         18    458
Thu       4       6         12    232
Fri       1       6          7    142

# comparisons Operations

In [62]:
a1, a2

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [64]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

In [76]:
a5 = np.random.randint(10, size=(3,5))
a5

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [89]:
a5

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [85]:
np.sort(a5)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]])

In [90]:
np.argsort(a5, axis=1)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]])

## Practical Example

<img src="/home/tyan/ML Course/ztm-ml/images/dog-photo-1.jpeg">

In [92]:
from matplotlib.image import imread

image = imread('/home/tyan/ML Course/ztm-ml/images/dog-photo-1.jpeg')

In [96]:
image.size, image.shape, image.dtype

(993600, (432, 575, 4), dtype('float32'))